kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-tmp
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"